- name: Create EC2  and R53
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0fd783259ba48c87f
    sg_id: sg-0996da6f4be0f2efc
    ami_id: ami-0ae0a4f69bf1ea649
    instances:
    - mysql
    - backend
    

  tasks: 
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    # tags:
    #   Environment: creating instance from ansible
    loop: "{{ instances }}"